prgrms-fe-devcourse/FEDC2_2JAVATAYO_Dongyoung

- package-lock.json
- package.json
- src/components/create/Select/Select.tsx
- src/components/create/Select/index.tsx
- src/pages/create.tsx
Select를 구현했습니다!
우선 Select는 Create, Edit 에만 사용될 컴포넌트라 별도로 만들었습니다. 
+ 이슈는 아니고 혹시 다른 분들도 antd 오류나실까봐 올려둡니당
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js): [1] Failed to parse source map: 'webpack://antd/./components/time-picker/style/index.less' URL is not supported
위와 같은 오류 해결방법입니다
```
import "antd/dist/antd.css";
```
```
import "antd/dist/antd.min.css";
```
@hwoo3303 님과 아래 부분 변수명을 통일해야합니당 
(이 값을 받아오셔야 detail 페이지에서도 보이니까용 !!)
```
const options = [
{ id: 1, value: "online", label: "온라인" },
{ id: 2, value: "offline", label: "오프라인" },
{ id: 3, value: "both", label: "온오프라인 병행" },
{ id: 4, value: "notyet", label: "미정" }
];
```
또한 통일이 되면 이 부분은 type 만을 정의한 곳으로 옮겨서 import해서 공통 코드를 줄여야할 것 같습니다!
값을 잘 받아오는지 콘솔에 테스트해보았습니당 😳
closes #24
> ✨ feat: Select 구현

- src/components/create/Cascader/Cascader.tsx
- src/components/create/Cascader/index.tsx
- src/pages/create.tsx
Cascader를 구현해보았습니다
Antd 특성상 선택된 값을 Array로 받아오는데 이는 어쩔 수 없을 거 같습니다..;;
이렇게 받아오더군요..;; ㅎㅅㅎ;; 
close #66
> :sparkles: feat: Cascader구현

- src/components/create/DatePicker/DatePicker.tsx
- src/components/create/DatePicker/index.tsx
- src/pages/create.tsx
`DatePicker`구현했습니다
2022/06/07 이런 느낌으로 데이터가 오게 됩니다 ! 
close #75
> :sparkles: feat: DatePicker 구현

- src/components/create/SelectBox/SelectBox.tsx
- src/components/create/SelectBox/index.tsx
- src/components/create/SelectBox/style.tsx
- src/pages/create.tsx
Label 을 포함한 SelectBox 구현
Select 에 Label을 추가하여 SelectBox를 만들었습니다.
이 때 마진과 패딩을 주었습니다 
close #67
> :sparkles: feat: SelectBox 구현

- src/components/common/ErrorMessage/ErrorMessage.stories.tsx
- src/components/common/ErrorMessage/ErrorMessage.tsx
- src/components/common/ErrorMessage/index.tsx
- src/components/common/ErrorMessage/style.tsx
- src/components/common/Input/Input.stories.tsx
- src/components/common/Input/Input.tsx
- src/components/common/Input/index.tsx
- src/components/common/Input/style.tsx
- src/components/common/Label/Label.stories.tsx
- src/components/common/Label/Label.tsx
- src/components/common/Label/index.tsx
- src/components/common/Label/style.tsx
: Input, Label, ErrorMessage 컴포넌트 구현
props
* type?: string
: 이메일, 비밀번호 같은 형식이 필요할 때
* width?: number;
: 기본 100% 크기에서 조절이 필요할 때
* placeholder?: string;
* value: string;
: 전달할 값
* onChange: React.ChangeEventHandler<HTMLInputElement>;
* name?: string;
: 값이나 에러처리 할 때 구분할 이름
props
* children
props
* children
close #19
> ✨ feat: Input, Label, ErrorMessage 컴포넌트 생성

- src/utils/apis/common.ts
process.env 불러오는 과정에서 팀원마다 다르게 동작하는 문제
기존 객체 분해 구조 할당문 대신 프로퍼티로 접근하도록 변경
closes #116
> 🐛 fix: process.env 수정

- src/components/common/Textarea/Textarea.stories.tsx
- src/components/common/Textarea/Textarea.tsx
- src/components/common/Textarea/index.tsx
- src/components/common/Textarea/style.tsx
Textarea 공통 컴포넌트 구현
(추가로 구현이 필요한 부분이 있다면 말씀 부탁드려요😀)
Textarea 유형
- 비로그인 상태
- 댓글 입력란
- 프로젝트 소개 입력란
사용 페이지
- 상세 페이지 : 댓글
- 게시글 작성 : 프로젝트 소개 작성란
- 게시글 수정 : 프로젝트 소개 작성란
스타일
|유형|값|
|-|-|
|width|700px|
|height|댓글 : 100px, 프로젝트 소개글 : 420px|
|border-radius|댓글 : 10px, 프로젝트 소개글 : 0px|
|overflow|댓글 : 스크롤, 프로젝트 소개글 : none(높이 자동 조절)|
https://user-images.githubusercontent.com/15838144/173251443-ca1b3b72-cced-422e-804c-8ffe306eae92.mov
closes #81
> ✨ feat: Textarea 공통 컴포넌트 구현

- src/components/common/Label/style.tsx
- src/components/create/InputBox/InputBox.stories.tsx
- src/components/create/InputBox/InputBox.tsx
- src/components/create/InputBox/style.tsx
```
<S.InputBox style={{ width }}>
<Label>{label}</Label>
<Input placeholder={placeholder} value={value} onChange={onChange} />
<ErrorMessage>{errorMessage}</ErrorMessage>
</S.InputBox>
```
* InputBox height: 90px로 고정
* width는 컴포넌트 사용시 조정가능 (픽셀 단위)
* margin: 4px 0
* font-weight: bold 삭제
close #36
> ✨ feat: InputBox 컴포넌트 생성

- src/components/create/DatePicker/DatePicker.tsx
- src/components/create/InputBox/style.tsx
- src/components/create/Select/Select.tsx
- src/components/create/SelectBox/SelectBox.tsx
- src/components/create/SelectBox/style.tsx
- src/pages/create/create.tsx
- src/pages/create/style.tsx
생성페이지 목업입니당
- [global fontSize 지정](https://github.com/prgrms-fe-devcourse/FEDC2_2JAVATAYO_Dongyoung/discussions/137)
close #134
> ✨ feat: 생성페이지 디테일 수정

- src/components/detail/PostBody/PostBody.tsx
- src/components/detail/PostBody/index.tsx
- src/components/detail/PostBody/style.tsx
- src/components/detail/PostHeader/PostSummary/style.tsx
- src/components/detail/PostHeader/style.tsx
- src/pages/detail.tsx
PostBody 컴포넌트 생성
상세 페이지 프로젝트 소개 영역 레이아웃을 생성했습니다.
- 서브 타이틀
- 소개글
- 수정, 삭제 버튼
- 디자인 및 이벤트 핸들링은 추후 구현 예정입니다.
closes #132
> ✨ feat: PostBody 컴포넌트 생성

- src/components/common/Header/Header.tsx
- src/components/common/TempLogin/index.tsx
TempLogin 컴포넌트 추가
| fullName | email | password |
|:---:|:---:|:---:|
|user1|user1@gmail.com|1234|
|user2|user2@gmail.com|1234|
| knk | knk@gmail.com|1234|
|유현naver|puh0128@naver.com|1234|
개발이후 제거
closes #156 
header 로그인
header 로그아웃
> ✨ feat: TempLogin 컴포넌트 추가

- src/components/common/AppLayout/style.tsx
- src/styles/reset.tsx
공통 style 수정
추가로 수정해야할 스타일이있으면 말씀해주세요~
#13
> 💄 style: 공통 style 수정

- src/components/common/Card/Card.stories.tsx
- src/components/common/Card/Card.tsx
- src/components/common/Card/style.tsx
- src/components/home/Filter/Filter.stories.tsx
- src/utils/Date.tsx
card 컴포넌트에 
(일부러그러는건지 모르겠는데 데이터를 0.5초씩 늦게 내려줌.)
closes #15 
#89 일부 완료
@YuHyun-P
>  ✨ feat: card컴포넌트에 데이터 입력

- src/components/create/Cascader/Cascader.jsx
- src/components/create/PartBox/PartBox.jsx
- src/components/create/PartBoxList/PartBoxList.jsx
- src/components/create/PartBoxList/index.tsx
- src/components/create/PartBoxList/style.tsx
- src/pages/create/create.tsx
PartBox를 추가할 때마다 PartBoxList를 리렌더링하여 구현하였습니다 (도움을 주신 팀원분들 감사합니다🙇🏻‍♀️)
로직이 복잡한데 이런식으로 props 내려서 하면 적합할지 봐주시면 감사하겠습니당
(+initialValue는 수정페이지에서 내려줘야할 값들이 있어서 지정한 props입니다! )
https://user-images.githubusercontent.com/72402747/174241549-4f89a7f4-56ec-4565-b7cb-29a7edfd4989.mov
close #149
> ✨ feat: PartBoxList구현

- src/components/common/Header/style.tsx
- src/components/profile/EditFullName/EditFullName.tsx
- src/components/profile/EditFullName/index.tsx
- src/components/profile/EditFullName/style.tsx
- src/components/profile/Modal/index.tsx
- src/components/profile/Modal/style.tsx
- src/components/profile/index.tsx
- src/pages/profile/profile.tsx
EditFullName 컴포넌트 구현 
- 프로필 페이지, 닉네임 변경을 위한 컴포넌트입니다.
- 에러 메세지 종류
- 2~8자 한글/영문/숫자 형식이 아닙니다
- 중복된 닉네임입니다
- 검증 로직
- 닉네임 형식(2~8자 한글/영문/숫자) 검증
- 서버통신으로 중복확인
- 사용 가능한 닉네임일 경우에만 `변경하기` 버튼이 활성화됩니다.
- Header 컴포넌트의 z-index값이 너무 커서 200으로 낮췄습니다
closes #180
> ✨ feat: EditFullName 컴포넌트 구현

- src/components/common/LikeBtn/LikeBtn.tsx
- src/styles/reset.tsx
likeBtn 오류 수정
- like갯수 오류 수정
- resetStyle color에 text들어있어서 수정
closes #185 
정상동작!
> 🐛 fix: likeBtn 오류 수정

- src/components/common/DropDown/style.tsx
- src/components/common/Header/Header.tsx
header에 DropDown 추가
closes #199
> ✨ feat: header에 DropDown 추가

- src/components/common/Card/Card.tsx
- src/components/common/Card/style.tsx
> ✨ feat: card 사이즈 고정, date 수정

- src/components/create/DatePicker/DatePicker.tsx
- src/components/create/PartBox/PartBox.jsx
- src/components/create/Select/Select.tsx
- src/components/create/SelectBox/SelectBox.tsx
- src/components/create/SelectBox/style.tsx
- src/pages/create/create.tsx
생성페이지 서버 통신 구현
라이브로 같이 확인한 부분이라 동영상은 따로 올리지 않겠습니당 
close #29
> ✨ feat: create 서버통신 구현

- src/components/create/Cascader/Cascader.jsx
- src/components/create/PartBox/PartBox.jsx
- src/pages/edit/edit.tsx
Edit 페이지 서버통신 구현
css 는 다녀와서 하도록 하겠습니당 !!
https://user-images.githubusercontent.com/72402747/174543456-83384c95-f45b-40aa-b638-d9c902a58c77.mov
close #32
> ✨ feat: 수정 서버 통신 구현

- src/components/common/Header/Header.tsx
- src/components/common/TempLogin/index.tsx
- src/contexts/AuthProvider.tsx
- src/pages/home/home.tsx
- src/pages/search/search.tsx
> ✨feat: contextAPI연결

- src/components/create/DatePicker/DatePicker.tsx
- src/pages/create/create.tsx
- src/pages/edit/edit.tsx
https://user-images.githubusercontent.com/72402747/174579319-9a1963aa-fde1-4824-b37a-73a435e3a5e8.mov
https://user-images.githubusercontent.com/72402747/174579425-b86816c3-39b1-403b-a2d8-5ac19a05d1be.mov
close #225
> 🐛 fix: DatePicker bug 수정

- src/components/create/Cascader/Cascader.jsx
- src/components/create/PartBox/PartBox.jsx
- src/components/create/PartBox/style.tsx
- src/components/create/SelectBox/style.tsx
- src/pages/create/create.tsx
- src/pages/create/style.tsx
생성페이지는 끝났습니당!! 수정 사항있으면 말해주세용 🙇🏻‍♀️
close #234
>  💄 style: 생성페이지 css 수정

- src/pages/create/create.tsx
- src/pages/edit/edit.tsx
- src/pages/edit/style.tsx
수정페이지도 css작업 완료했습니다.
원래는 ImageUploader도 넣으려고 하였는데, 형진님이 다른 작업중이신거 같아서 pr 올립니당
이미지 부분은 따로 이슈를 생성할게욤 
close #236
> :lipstick: style: 수정페이지 css 작업

- src/components/detail/PostBody/PostBody.tsx
- src/components/detail/PostBody/style.tsx
- src/components/detail/PostFooter/TextareaBox/TextareaBox.tsx
- src/pages/detail/detail.tsx
댓글 작성 시 알림 생성
- 댓글 작성 시 알림 생성
- 생성 페이지로 가는 navigate에 imagePublicId 추가
- 알림 생성 확인
- 상세 페이지 첨부 이미지
closes #235
> ✨ feat: 댓글 등록 시 알림 생성

- src/components/detail/PostFooter/Comment/Comment.tsx
- src/components/detail/PostFooter/PostFooter.tsx
- src/components/detail/PostHeader/PostHeader.tsx
- src/pages/detail/detail.tsx
상세페이지 프로필 사진 클릭 시 해당 유저 프로필 페이지로 이동
클릭 이벤트 추가
- 게시물 작성자 프로필
- 댓글 작성자 프로필
서버에서 받아오는 시간 변경
- 댓글 updatedAt 한국시간으로 변경
closes #252 
https://user-images.githubusercontent.com/15838144/174727178-86c2127f-c2b5-46fc-b31b-85be9adedca6.mov
> ✨ feat: 상세페이지 프로필 사진 클릭 시 해당 유저 프로필 페이지로 이동

- src/pages/create/create.tsx
- src/pages/edit/edit.tsx
> :bug: fix: edit page select defaultValue 설정

- .eslintrc.json
- package.json
- src/components/detail/TextareaBox/TextareaBox.tsx
error가 나면 husky가 자동으로 commit을 막아줍니다! 
close #289
> :wrench: config: 불필요한 eslintConfig 삭제 후 .eslintrc.json으로 통일

- src/components/common/Header/Header.tsx
- src/components/common/LikeBtn/LikeBtn.tsx
- src/components/home/HomeFilter/HomeFilter.tsx
- src/components/search/SearchFilter/SearchFilter.tsx
♻️ refactor: home, search 페이지 경로별칭 수정
♻️ refactor: home, search 페이지 경로별칭 수정
closes #313
> ♻️ refactor: home, search 페이지 경로별칭 수정

- src/components/common/InputBox/InputBox.tsx
- src/components/common/InputBox/style.ts
- src/contexts/AuthProvider.tsx
- src/pages/signIn/signIn.tsx
- src/pages/signUp/signUp.tsx
> ♻️ refactor: 로그인, 회원가입, InputBox, Context 경로별칭 수정

- src/components/detail/Comment/Comment.tsx
- src/components/detail/PostBody/PostBody.tsx
- src/components/detail/PostFooter/PostFooter.tsx
- src/components/detail/PostHeader/PostHeader.tsx
- src/components/detail/PostSummary/PostSummary.tsx
- src/components/detail/TextareaBox/TextareaBox.tsx
상세보기 페이지 경로 별칭 수정
상세보기 페이지에 관련된 컴포넌트들 경로 별칭 수정
closes #315
> ♻️ refactor: 상세보기 페이지 경로 별칭 수정

- src/pages/create/create.tsx
- src/pages/edit/edit.tsx
- 비로그인 상태에서는 edit, create 접근 못 하도록 설정
- [현진님의 pr](https://github.com/prgrms-fe-devcourse/FEDC2_2JAVATAYO_Dongyoung/pull/308) 참고하여서 진행하였습니다! 감사해용 !! 
blocker는 우선은 뺐습니다!
close #309
> 🐛 fix: 비로그인상태에서는 edit / create 페이지 접근 못 하도록 수정

- src/pages/search/search.tsx
검색기능 수정
searchAPI에서 post외에 user에대한 정보도 같이 내려와서 오류가 있었습니다. 
중간에 필터로 user에대한 배열을 제거해주고 post에대한 정보만 필터링되도록 수정했습니다~
closes #323
> 🐛 fix: 검색기능 수정

- src/pages/create/create.tsx
focus만으로는 부족한 거 같아서 alert 추가했습니당 
https://user-images.githubusercontent.com/72402747/174969166-cf743fb9-0358-4a4e-a423-9dc99c0e513f.mov
close #331
> :sparkles: feat: validation 통과 못 할 경우 alert메시지 출력

- src/pages/detail/detail.tsx
상세 페이지 ai 채널 조회 대문자에서 소문자로 변경
상세 페이지 ai 채널 조회 대문자에서 소문자로 변경
closes #345
> 🐛 fix: 상세 페이지 ai 채널 조회 대문자에서 소문자로 변경
