- src/App.tsx
- src/style/reset.tsx
- src/styles/reset.tsx
* reset css 설정
* noto-sans kr을 전체 적용 폰트로 지정 (Roboto 폰트는 추가만)
```
<h1>안녕</h1>
<p>안녕</p>
<h1>Hello</h1>
<p>Hello</p>
```
Close #68
> 💄  style: reset css 설정

- src/components/common/AppLayout/AppLayout.stories.tsx
- src/components/common/AppLayout/AppLayout.tsx
- src/components/common/AppLayout/index.tsx
- src/components/common/AppLayout/style.tsx
`AppLayout` 컴포넌트 추가
- children으로 내부 컨텐츠 받습니다.  
- max-width가 700px 이고 이후 이보다 작으면 좌우 18px의 패딩이 생기며 좌우 간격을 유지시켜줌니다.
- Header와 Footer는 임시로 자리만 잡아놨습니다. 이후 컴포넌트로 추가 예정
`AppLayout` 컴포넌트
> ✨ feat: AppLayout 컴포넌트 추가

- .gitignore
- package-lock.json
- package.json
- src/types/apis.ts
- src/types/model.ts
- src/utils/apis/auth.ts
- src/utils/apis/channel.ts
- src/utils/apis/comment.ts
- src/utils/apis/common.ts
- src/utils/apis/follow.ts
- src/utils/apis/index.ts
- src/utils/apis/like.ts
- src/utils/apis/notification.ts
- src/utils/apis/post.ts
- src/utils/apis/search.ts
- src/utils/apis/setting.ts
- src/utils/apis/user.ts
- src/utils/storage.ts
API 구현
메시지 API는 당장 필요하지 않아서 추가하지 않았습니다.
- JWT 토큰이 필요한 API
- 요청 전에 인터셉터를 이용해 우선 로컬 스토리지에 저장된 `TOKEN`키 값을 사용해 요청하도록 구현했습니다.
- 논의할 점
- 현재 구현된 것처럼 API에서 토큰을 자동으로 추가할지 API 인수로 토큰을 전달받을지
- 토큰을 어디에 저장할지
- 로컬 스토리지로 정해진다면, 키 값은 "TOKEN"이 괜찮은지  
- 로그아웃 API는 현재 백엔드에서 제대로 동작하지 않고 있는 것 같습니다(?).
- 로그인, 사용자 검색, 인증 확인 API 만 테스트해보고 다른 API는 시간이 부족한 관계로 테스트하지 못 했습니다. 각자 페이지에서 사용해보시면서 API 에러가 발견되면 Issue로 알려주시면 감사하겠습니다🙇‍♀️
- 타입스크립트 인터페이스를 나름 작성해 봤는데 고칠 점이 있다면 알려주시면 감사하겠습니다!
closes #28
> ✨ feat: API 추가

- .storybook/main.js
- src/hooks/useClickAway.stories.tsx
- src/hooks/useClickAway.ts
프로필 페이지 Modal 컴포넌트 구현을 위한 useClickAway 훅 추가
프로필 페이지에서만 사용될 것 같지만 따로 빼냈습니다. 
**인수**: 클릭 이벤트 핸들러
**반환값**: HTML 요소에 접근이 가능한 ref를 반환합니다
useClickAway는 모달 컴포넌트와 주로 같이 사용하는데 모달 영역 밖을 클릭했을 때 모달이 닫히는 기능 구현을 위해 사용됩니다. useClickAway 훅의 인수로 **모달이 닫히는 이벤트 핸들러**를 전달하고, 반환된 **ref를 속성을 모달에 설정**해서(=`ref={ref}`) 사용합니다.
closes #104
> ✨ feat: useClickAway 훅 추가

- craco.config.js
- package-lock.json
- package.json
- src/components/common/Footer/Footer.tsx
- src/components/common/SkillIcon/index.tsx
- src/components/profile/CoverImage/index.tsx
- tsconfig.json
- tsconfig.paths.json
path alias 설정이 적용되지 않던 문제
**CRA** + craco + typescript 환경에서는 [react-app-alias](https://github.com/oklas/react-app-alias#using-craco) 패키지를 이용해 path alias를 설정해야 하더군요..새로운 패키지를 설치해서 해당 브랜치가 머지되면 `npm i` 한 번 해주셔야 제대로 path alias를 사용하실 수 있을 것이에요!
`@assets`, `@components`, `@constants`, `@contexts`, `@hooks`, `@pages`, `@utils `추가 했습니다. 
- `@types`, `@styles` 별칭도 만들고 싶었으나 기존 패키지와 겹쳐서 설정하지 못 했습니다😅
closes #102
> 🐛 fix: path alias 설정이 적용되지 않던 문제

- src/components/common/Card/Card.stories.tsx
- src/components/common/Card/Card.tsx
card 컴포넌트 오류
- 지금 backend에서 skill, 프로젝트기간, 모집인원 등 받아올 수 없어서 임시로 대체 텍스트 넣어두었습니다.
-  post를 넣지않으면 오류가나와야하지만 **임시로** post가 들어가지 않아도 더미 데이터가 들어가도록 변경했습니다.
close #127 
@YuHyun-P 필수
@hwoo3303 , @Hyevvy  , @hyunjin0910 중 1분 부탁드려요~
> 🐛 fix: type오류로 임시 dummy 데이터 추가

- src/assets/icons/icon_close.svg
- src/components/profile/Modal/Modal.stories.tsx
- src/components/profile/Modal/index.tsx
- src/components/profile/Modal/style.tsx
- src/components/profile/index.tsx
- src/hooks/index.tsx
프로필 페이지에 사용될 Modal 컴포넌트를 구현했습니다.
- children
- 모달 안에 들어갈 컴포넌트들입니다.
- height
- 모달의 높이입니다. 문자열로 받기 때문에 px, % 모두 사용 가능합니다.
- visible
- 배경과 모달의 display 값을 block, none 으로 토글하는 불리언 값입니다.
- onClose
- 모달 영역 밖을 클릭하거나 모달 내 X 버튼을 누를 때 호출되는 콜백 함수입니다.
**스토리북 Default**
closes #101
> ✨ feat: Modal 컴포넌트 구현

- .storybook/main.js
- package-lock.json
- package.json
- tsconfig.json
- tsconfig.paths.json
스토리북 실행 환경에서도 추가 설정이 필요하더군요..
역시나 추가된 패키지가 있으므로 `npm i` 하셔야 합니당
- contexts 폴더에 실험할 파일이 없어서 테스트는 못 했습니다
**로컬 서버**
**스토리북**
**위 환경에서 테스트할 때 사용한 코드 일부**
```js
import Footer from "@components/common/Footer";
import defaultCoverImage from "@assets/imgs/profile_default_cover.png";
import skillOptions from "@constants/skill";
import { useHover } from "@hooks";
import { channelAPI } from "@utils/apis";
```
closes #102
> 🐛 fix: 스토리북 path alias 적용 문제

- src/pages/create/create.tsx
- src/routes/Blocker.js
라우터에서 처리할까 하다가 생성, 수정페이지 (혜경) + 프로필페이지 (유현) + 회원가입페이지 (현진)에만 쓰이는 건데 전체에 넣는건 아닌 거같아서요! 각자 페이지에서 처리하는건 어떨까요?
Block.js를 구현하였습니다.
사용법은 다음과 같습니다.
```
import { usePrompt } from "../../routes/Blocker";
usePrompt("현재 페이지를 벗어나시겠습니까? ", true); // " " 안에 사용하고자하는 문구를 적으면 됩니다!
```
close #139 
이 부분은 추후에 custom도 가능한데 우선 급한거는 아니기에 기능만 구현하였습니다
> :sparkles: feat: blocker.js구현

- src/components/profile/Tab/TabItem.tsx
- src/components/profile/Tab/index.tsx
- src/components/profile/Tab/style.tsx
- src/components/profile/index.tsx
- src/pages/profile/profile.tsx
페이지 이동 없이 콘텐츠를 스위칭할 수 있는 Tab 컴포넌트 구현 
Tab컴포넌트의 currentActive 상태값에 따라 보여주는 콘텐츠와 TabItem의 props.active값이 변경됩니다.
짝꿍 @NamgyungKim 🥰
closes #100
> ✨ feat: Tab 컴포넌트 구현

- src/components/profile/EditIcon/index.tsx
- src/components/profile/ProfileImageBox/index.tsx
- src/components/profile/ProfileImageBox/style.tsx
- src/components/profile/index.tsx
- src/pages/profile/profile.tsx
- src/pages/profile/style.tsx
프로필 페이지에서 사용할 CoverImageBox 컴포넌트 구현
- 서버 통신하는 동안 로딩 중임을 알리는 스켈레톤 컴포넌트가 필요해 보입니다. 
- isLoading 변수를 #151 로 관리해야 할 것 같습니다.
- 우선 서버 통신 기능을 해당 컴포넌트 내부에 작성했지만, 프로필 이미지가 변경되면 #151 값이 변경되는 것과 같으므로 action에서 해야 할 것 같습니다.
- 서버 통신은 현재 주석 처리를 해서 제대로 동작하지 않습니다. 기능을 테스트하려면 components/profile/ProfileImageBox/index.tsx 파일에서 주석을 제거해야 할 수 있습니다.
⚠아래 gif는 CoverImageBox 컴포넌트 구현이 끝난 상태로 촬영해 커버 이미지가 보이지만 현재 PR 날리는 코드 상으로는 CoverImageBox 컴포넌트 구현 전이라 커버 이미지가 없습니다!!
closes #144
> ✨ feat: ProfileImageBox 컴포넌트 구현

- src/components/profile/CoverImageBox/index.tsx
- src/components/profile/CoverImageBox/style.tsx
- src/components/profile/ProfileImageBox/index.tsx
- src/components/profile/index.tsx
- src/pages/profile/profile.tsx
프로필 페이지 CoverImageBox 컴포넌트 구현
- CoverImage (커버 이미지 출력) + ImageUpload (이미지 파일 받기) + EditIcon (ImageUpload의 input:file 스타일 덮어쓰기) 컴포넌트들의 조합으로 만들었습니다.
- `커버 이미지 변경` 서버 통신 연결 (UserContext로 이관할 예정)
- ProfileImageBox 컴포넌트 코드와 거의 유사해서..마음이 불편하지만 추후에 시간이 된다면 리팩토링하겠습니다
- User 정보를 받아오는 서버 통신은 연결하지 않고 더미 데이터로 하기 때문에 첫 페이지에 보이는 커버 이미지는 실제 유저의 커버 이미지와 다를 수 있습니다
closes #159 
짝꿍 @NamgyungKim
> ✨ feat: CoverImageBox 컴포넌트 구현

- src/hooks/index.tsx
- src/hooks/useAxios.ts
- src/hooks/useAxiosFn.ts
서버 통신에 사용할 useAxiosFn, useAxios 훅 구현
- useAxiosFn
- 반환되는 axios 함수의 콜백 함수를 서버 통신이 필요한 때에 맞게 호출하면 됨
- axios 함수를 첫번째 인수로 전달
- 두번째 인수로 의존성 전달
- 반환값
- [ { isLoading, response, error }, axios 함수의 콜백 함수 반환 ]
- useAxios
- **페이지가 마운트 될 때** 인수로 전달한 axios 함수를 한 번 실행되는 훅
- { isLoading, response, error } 값 반환
- 두번째 인수로 의존성 전달
closes #188
> ✨ feat: useAxiosFn, useAxios 훅 구현

- src/utils/storage.ts
로컬 스토리지의 getItem, removeItem 메서드에 대한 지식이 잘못된 상태에서 구현했습니다.
- getItem
- 실제 로컬 스토리지의 `getItem` 메서드는 인수로 전달하는 키 값이 없으면, 에러를 발생시키지 않고 `null` 값을 반환
- removeItem
- 실제 로컬 스토리지의 `removeItem` 메서드는 인수로 전달하는 키 값이 없어도 에러 발생 X
- getItem 인수로 전달하는 key 값이 없으면 initialValue를 반환하도록 변경
- removeItem 함수 내부에 실행될 수 없는 에러 핸들링 제거
closes #189
> 🐛 fix: getItem, removeItem 불필요한 에러 핸들링 제거

- src/components/common/DropDown/DropDown.stories.tsx
- src/components/common/DropDown/DropDown.tsx
- src/components/common/DropDown/index.tsx
- src/components/common/DropDown/style.tsx
DropDown 컴포넌트 추가
- props로 top, left를 num으로 받아 DropDown위치 지정가능
- 내부 컨텐츠 내용과 함수는 아래 배열 모양으로 넘겨준다.
```
const contents = [
{
label: "닉네임변경",
event: () => event(1)
},
{
label: "비밀번호 변경",
event: () => event(2)
},
{
label: "프로필 변경",
event: () => event(3)
}
];
```
```js
<DropDown contents={contents}>
<button>드롭다운</button>
</DropDown>
```
- children과 contents만 필수값이다.
- top: 50px, left: 0px 이 기본값이다.
closes #181
> ✨ feat: DropDown 컴포넌트 추가

- src/types/apis.ts
- src/utils/apis/follow.ts
- src/utils/apis/like.ts
- src/utils/apis/notification.ts
- src/utils/apis/post.ts
- src/utils/apis/user.ts
서버 통신 중 offset, limit 값을 필요로 하는 API 함수에서 해당 값을 Request parameter로 요청하도록 변경
- userAPI
- getUserList (사용자 목록을 불러옵니다.)
- postAPI
- getChannelPostList (특정 채널의 포스트 목록을 불러옵니다.)
- getUserPostList (특정 사용자의 포스트 목록을 불러옵니다.)
- allPost (전체 포스트 목록을 불러옵니다.)
- offset, limit은 옵셔널 값이므로 기존 코드도 에러 없이 잘 동작합니다!
(offset=0번부터 limit=1개만 가져오도록!)
- notificationAPI
- seenNotification (나에게 온 알림을 읽음 처리합니다)
closes #192
> 🐛 fix: 서버 API 오류

- src/components/common/Textarea/Textarea.tsx
- src/components/common/Textarea/style.tsx
- src/components/detail/PostBody/PostBody.tsx
- src/components/detail/PostFooter/Comment/Comment.tsx
- src/components/detail/PostFooter/PostFooter.tsx
- src/components/detail/PostFooter/TextareaBox/TextareaBox.tsx
- src/components/detail/PostHeader/PostHeader.tsx
- src/components/detail/PostHeader/PostSummary/PostSummary.tsx
- src/pages/detail.tsx
작업량이 많아져서 PR을 나누고 중간병합을 하려합니다.
- Textarea 스타일 수정
- 댓글 등록 및 삭제 서버통신 구현
- 게시글 상세 보기 서버통신 구현
- 계정에 따라 보여줘야되는 요소 분기처리 작업 필요
- 댓글을 등록한 후에 바로 삭제하면 페이지에서 바로 반영이 되지 않아요. 이 부분은 다음 PR때 반영하려합니다.
- 수정 페이지로 넘기는 Navigate 부분도 다음 PR때 반영하겠습니다.
- 상세 페이지 상단의 화살표 아이콘과 좋아요 기능도 구현해야됩니다.(이건 금방 할 수 있을거같아요!)
- 프로젝트 소개글
- 댓글 작성 기능
https://user-images.githubusercontent.com/15838144/174494133-23be176b-37df-478b-845d-e581572eeabb.mov
- 댓글 삭제 기능
https://user-images.githubusercontent.com/15838144/174494156-08370c80-0156-487a-98e2-39ff00009286.mov
closes #174
> ✨ feat: 상세 페이지 서버통신 구현

- src/components/common/Textarea/Textarea.tsx
- src/components/detail/PostFooter/TextareaBox/TextareaBox.tsx
- src/pages/detail/detail.tsx
- src/pages/detail/index.tsx
수정페이지 navigate 구현
- 상세페이지 -> 수정페이지 navigate 구현
|변수명|용어|
|-|-|
|postId|게시글 ID|
|title|제목|
|place|진행 방식|
|email|연락 방법|
|startDate|시작일|
|expectedDate|예상 기간|
|channel|모집분야|
|people|모집인원|
|skills|기술스택|
|introduction|소개글|
|images|이미지 정보|
- Textarea useRef prop 추가
- 이미지 정보는 아직 api 서버쪽에 데이터가 없어서 제대로 테스트가 안됐습니다. 
(생성페이지에서 이미지가 있는 게시글 생성 시 데이터 확인 필요)
- location log
- Textarea focus
https://user-images.githubusercontent.com/15838144/174501860-8b2d6060-a2a6-46dd-a994-51a21d481f09.mov
closes #209
> ✨ feat: 수정페이지 navigate 구현

- src/hooks/useSignIn.tsx
- src/pages/signIn/signIn.tsx
- src/pages/signIn/style.tsx
로그인 페이지 API 통신 조건 수정
로그인 submit 시 
API 통신 에러가 발견하면 에러 메세지를 설정하는 방식 -> 에러 메세지가 아닌 경우에만 유효한 계정인지 API 통신을 하는 방법으로 변경했습니다
thanks to @YuHyun-P 
close #206
> 🐛 fix: 로그인 페이지 에러 형식 확인 후 API 요청으로 수정

- src/components/detail/PostBody/PostBody.tsx
- src/components/detail/PostFooter/Comment/Comment.tsx
- src/components/detail/PostFooter/PostFooter.tsx
- src/components/detail/PostFooter/TextareaBox/TextareaBox.tsx
- src/components/detail/PostHeader/PostHeader.tsx
- src/pages/detail/detail.tsx
상세 페이지 post 삭제, 좋아요, 권한 작업
- 게시글 삭제 API 통신 추가
- 좋아요 기능 추가
- 권한 별로 수정/삭제, 댓글 등록/삭제 요소 다르게 보이기
- 댓글 등록 시 setState에 추가 Comment 추가 부분에서 Comment id를 불러오는 방법을 찾아야됩니다.
- 게시글 삭제
https://user-images.githubusercontent.com/15838144/174574411-c565a2a5-4cde-4f16-b60f-b3d56ce699b1.mov
- 좋아요/해제
https://user-images.githubusercontent.com/15838144/174574890-a9577416-4dee-4527-8998-4b013c34f8ff.mov
- 권한 처리
https://user-images.githubusercontent.com/15838144/174575227-d0656144-dbff-4a4c-8b54-e26eb1f017ad.mov
closes #220
> ✨ feat: 상세 페이지 post 삭제, 좋아요, 권한 작업

- src/components/signUp/index.tsx
- src/hooks/useSignUp.tsx
- src/pages/signUp.tsx
- src/pages/signUp/index.tsx
- src/pages/signUp/signUp.tsx
- src/pages/signUp/style.tsx
- src/routes/Router.tsx
회원 가입 페이지 구현
* 각 값에 따른 에러메세지 노출
* 닉네임 중복 확인을 하지 않으면 가입이 되지 않음 (중복 확인 요청 alert)
* 회원 가입 성공 시 로그인한 상태로 **메인으로 이동** 
(이게 더 나아보여서 로그인 페이지 대신 메인으로 이동하는 것으로 했습니다, 수정 필요하면 말씀해주세요!)
✅  API 구조상 닉네임이 안겹치면 예전에 가입한 이메일로도 가입 가능...
✅  로그인 페이지와 겹치는 내용이 많아서 merge후 같이 리팩토링하려고 합니다 
close #38 
https://user-images.githubusercontent.com/95457808/174561208-06a675d4-7153-4141-8c9a-01a354853c5e.mp4
https://user-images.githubusercontent.com/95457808/174560487-dcd7306b-6c86-4e5b-89f1-ed58120a60d9.mp4
> ✨ feat: 회원 가입 페이지 구현

- src/components/create/ImageUploader/ImageUploader.tsx
- src/pages/create/create.tsx
(형진님 상세페이지에서 이미지 보이도록  + 수정페이지로 넘기실 때 PublicId도 .. 부탁드려용 😳)
완료 후 PublicId를 잘 받아오고 있습니다
close #228
> :sparkles: feat: 생성페이지에서 ImageUploader 서버 통신 구현

- src/components/detail/PostFooter/Comment/Comment.tsx
- src/components/detail/PostFooter/PostFooter.tsx
- src/components/detail/PostFooter/TextareaBox/TextareaBox.tsx
- src/components/detail/PostHeader/PostHeader.tsx
- src/pages/detail/detail.tsx
[상세페이지] 프로필 사진 조회 수정, 댓글 등록 비동기 방식 구현
프로필 사진 조회
- 게시물 작성자, 댓글 작성자의 프로필 사진이 안보이는 현상 fix
댓글 등록
- 댓글 등록 후 Location.reload()에서 댓글 상태 관리를 통해 비동기 방식으로 fix
- 댓글 등록 후 알림 대상을 게시물 작성자로 fix
시간
- 게시글의 updatedAt 정보를 현지 시간으로 변경 
closes #239 
- 게시글 작성자 프로필 정보
- 댓글 작성자 프로필 정보
- 댓글 비동기 처리
https://user-images.githubusercontent.com/15838144/174671508-8121c548-ea87-4a59-9a86-48b4cc8afe20.mov
> 🐛 fix: [상세페이지] 프로필 사진 조회, 댓글 등록 기능 fix

- src/pages/create/create.tsx
- src/pages/edit/edit.tsx
[잘만 되던 수정, 생성시 메인페이지 navigate 기능](https://github.com/prgrms-fe-devcourse/FEDC2_2JAVATAYO_Dongyoung/pull/221) 이 갑자기 안 되었음
-> 왜지.. ?? 
-> 알고보니 **서버 응답값이 갑자기 바뀜 ㅠ ㅠ** 
이전에는 statusText 가 Ok였는뎅,, 
바뀐 서버 응답값을 보니 statusText 비어있음 ㅠ
그래서 그냥 `status === 200` 으로 제 자신과 원만한 합의봤네요
⭐️ 생성시 잘 되는 증거영상
https://user-images.githubusercontent.com/72402747/174844140-a0219f09-e3a4-4840-a82e-3caaf0ea443e.mov
⭐️ 수정시 잘 되는 증거영상 
https://user-images.githubusercontent.com/72402747/174844152-ec53b7a6-6c50-4a9f-ae41-d7c6c45d6148.mov
close #294
> 🐛 fix: 글 생성, 수정 이후 메인페이지 navigate 안 되던 버그 수정

- src/pages/signIn/signIn.tsx
- src/pages/signUp/signUp.tsx
🐛 bug: 로그인 상태에서 로그인, 회원가입 페이지 접근 시 메인으로 돌리기
**이전**
로그인 상태
-> 로그인 페이지: 404 페이지
-> 회원가입 페이지: 접속 가능 (단 url에 유저가 직접 치고 들어가야 함)
**변경 후**
로그인 상태 시 메인으로 바로 이동
close #300
> 🐛 bug: 로그인 상태에서 로그인, 회원가입 페이지 접근 시 메인으로 돌리기

- src/components/detail/PostHeader/PostHeader.tsx
기존에는 비회원도 좋아요 영역에 마우스를 올리면  cursor: pointer 처리가 되었음
상세페이지 게시글 좋아요 영역에 비회원은 cursor: default 처리
closes #333
> 🐛 fix: 상세페이지 게시글 좋아요 영역에 비회원은 cursor: default 처리

- src/components/common/BottomSheet/BottomSheet.tsx
- src/components/common/Footer/Footer.tsx
- 사용자 검색 조건 필터가 equal로 되어있어 검색에 불편함이 있음
- Enter KeyUp 이벤트가 없어 검색에 불편함이 있음
Search API 사용하니까 4시간 걸려서 지지고 볶고 구현하던 부분이 10분으로 단축되었네요... 🥲
- 사용자 검색 조건 필터를 equal에서 like로 변경
- Enter KeyUp으로 검색 추가
- BottomSheet 페이지 별로 show/hide 처리
closes #338
> 🐛 fix: 사용자 검색 조건 필터를 equal에서 like로 변경, 엔터로 검색 추가, BottomSheet 페이지 별로 show/hide 처리
